---
  - hosts: ubuntu
    gather_facts: True

    tasks:
      - name: Atualizando o apt-cache
        apt:  update_cache=yes cache_valid_time=3600
        become: yes

      - name: Instalando o Python3
        apt: name={{ item }} state=present
        become: yes
        loop:
          - python3
          - virtualenv
      
      - name: Criando a venv e instalando dependências
        pip:
          virtualenv: /home/ubuntu/tcc/venv
          name:
            - django
            - djangorestframework

      - name: Verificando se o projeto ja existe
        stat:
          path: /home/ubuntu/tcc/setup/settings.py
        register: projeto

      - name: Iniciando o projeto
        shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
        when: not projeto.stat.exists

      - name: Alterando o hosts settings
        lineinfile:
          path: /home/ubuntu/tcc/setup/settings.py
          regexp: 'ALLOWED_HOSTS'
          line: "ALLOWED_HOSTS = ['*']"
          backrefs: yes
        tags:
          - hosts
      
      - name: Subindo o ambiente para teste (Ctrl + C para sair)
        shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py runserver 0.0.0.0:8000'
        tags:
          - runserver
