---
  - hosts: all
    gather_facts: True
    become: yes

    tasks:
      - name: Atualizando o apt-cache
        apt:  update_cache=yes cache_valid_time=3600
        become: yes
      
      - name: Instalando o Python3
        apt: name={{ item }} state=present
        become: yes
        loop:
          - python3
          - virtualenv