---
  - name: Criando a venv e instalando dependências
    pip:
      virtualenv: '{{ venv_dir }}'
      name:
        - django
        - djangorestframework
  
  - name: Verificando a existência do Projeto
    stat:
      path: '{{ root_dir }}/setup/settings.py'
    register: projeto
  
  - name: Iniciando o projeto
    shell: '. {{ venv_dir }}/bin/activate; django-admin startproject setup {{ root_dir }}'
    when: not projeto.stat.exists
  
  - name: Alterando o hosts no settings.py
    lineinfile:
      path: '{{ root_dir }}/setup/settings.py'
      regexp: 'ALLOWED_HOSTS'
      line: "ALLOWED_HOSTS = ['*']"
      backrefs: yes
  
  - name: Iniciando o ambiente
    shell: '. {{ venv_dir }}/bin/activate; nohup python {{ root_dir }}/manage.py runserver 0.0.0.0:8000 &'