---
  - hosts: ubuntu
    gather_facts: False

    tasks:
      - name: Criando o arquivo
        copy:
          dest: /home/$USER/index.html
          content: <h1>Hello world!</h1>
      
      - name: Criando o servidor web
        shell: "nohup busybox httpd -f -p 8080 &"