---
  - hosts: ubuntu
    gather_facts: True

    tasks:
      - name: Atualizando o apt-cache
        apt:  update_cache=yes cache_valid_time=3600
        become: yes

      - name: Instalando o Python3
        apt: name={{ item }} state=present
        become: yes
        loop:
          - python3
          - virtualenv
      
      - name: Criando a venv e instalando dependências
        pip:
          virtualenv: /home/ubuntu/tcc/venv
          name:
            - django
            - djangorestframework

      - name: Iniciando o projeto
        shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
      
      - name: Alterando o hosts settings
        lineinfile:
          path: /home/ubuntu/tcc/setup/settings.py
          regexp: 'ALLOWED_HOSTS'
          line: "ALLOWED_HOSTS = ['*']"
